name: Amlogic_ImmortalWrt Builder

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-22.04
    steps:
    - name: package
      run: 
        sudo apt-get update -y
        sudo apt-get full-upgrade -y
        sudo apt-get install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
        git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
        mkdir /amlogic-s9xxx-openwrt/openwrt-armvirt
        wget https://downloads.immortalwrt.org/releases/23.05.4/targets/armsr/armv8/immortalwrt-23.05.4-armsr-armv8-generic-squashfs-rootfs.img.gz
        mv immortalwrt-23.05.4-armsr-armv8-generic-squashfs-rootfs.img.gz /amlogic-s9xxx-openwrt/openwrt-armvirt/openwrt-armvirt-64-default-rootfs.tar.gz
        cd amlogic-s9xxx-openwrt
        sudo ./remake -b s905x3 -k 6.1.10

