#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Amlogic_ImmortalWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo apt-get update
        sudo apt-get full-upgrade
        sudo apt-get install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
        sudo mkdir -p /amlogic-s9xxx-openwrt/openwrt-armvirt
        wget https://downloads.immortalwrt.org/releases/23.05.4/targets/armsr/armv8/generic-squashfs-rootfs.img.gz /amlogic-s9xxx-openwrt/openwrt-armvirt/
        cd amlogic-s9xxx-openwrt
        sudo ./remake -b s905x3 -k 6.1.10

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: amlogicimmortalwrt
        path: ./out/*
